import GeneralStyle from './GeneralStyle';
import ComponentStyle from './ComponentStyle';
import NavigationStyle from './NavigationStyle';
import EditorStyle from './EditorStyle';
import Colors from './Colors';
import Fonts from './Fonts';
import Dimensions from './Dimensions';
import TextStyles from './TextStyles';
import MyDirectionsStyle from './MyDirectionsStyle';
import ButtonStyles from './ButtonStyles';
import ExerciseDetailStyle from './ExerciseDetailStyle';
import MyExercisesStyle from './MyExercisesStyle';
import OnboardingStyle from './OnboardingStyle';
import DeploymentStyle from './DeploymentStyle';
import AnalyticsStyles from './AnalyticsStyles';
import TrainingStyle from './TrainingStyle';
import LoginStyle from './LoginStyle';

exports.GeneralStyle = GeneralStyle;
exports.ComponentStyle = ComponentStyle;
exports.NavigationStyle = NavigationStyle;
exports.EditorStyle = EditorStyle;
exports.Colors = Colors;
exports.Fonts = Fonts;
exports.Dimensions = Dimensions;
exports.TextStyles = TextStyles;
exports.MyDirectionsStyle = MyDirectionsStyle;
exports.ButtonStyles = ButtonStyles;
exports.ExerciseDetailStyle = ExerciseDetailStyle;
exports.MyExercisesStyle = MyExercisesStyle;
exports.OnboardingStyle = OnboardingStyle;
exports.DeploymentStyle = DeploymentStyle;
exports.AnalyticsStyles = AnalyticsStyles;
exports.TrainingStyle = TrainingStyle;
exports.LoginStyle = LoginStyle;
